# Generated by Django 4.2.5 on 2023-09-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pengaduan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("nip", models.IntegerField()),
                ("nik", models.IntegerField()),
                (
                    "email",
                    models.EmailField(
                        default=".tte@deliserdangkab.go.id", max_length=254
                    ),
                ),
                ("dinas", models.CharField(max_length=400)),
                ("nohp", models.IntegerField()),
                ("keluhan", models.TextField()),
                ("publish", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
